version: '3'

services:

  web_app:
    build: ./
    restart: always
    depends_on:
      - db
    command: 'streamlit run main.py --server.port=8501 --server.address=0.0.0.0'
    ports:
      - 8501:8501
    networks:
      - postgres-network

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  pgdata:
  pgadmin-data:

networks: 
  postgres-network:
    driver: bridge